runtime: java
entrypoint: java -Xmx64m -jar everything-project.jar
env: flex
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"
env_variables:
  SPRING_PROFILES_ACTIVE: "server"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
