spring:
  jpa:
    show-sql: false
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AZURE_MYSQL_URL}
    username: ${AZURE_MYSQL_USER}
    password: ${AZURE_MYSQL_PASSWORD}
    hikari.data-source-properties:
      useSSL: true
      useUnicode: true
      socketTimeout: 1800000
      connectTimeout: 10000
      characterEncoding: utf8
      allowPublicKeyRetrieval: true
      jdbcCompliantTruncation: false
      createDatabaseIfNotExist: true
  liquibase:
    enabled: true
    drop-first: false

server:
  port: 8080
  servlet.session.timeout: 1800
  tomcat.accesslog.enabled: true
  address: ${APP_SERVICE_IP}
