spring:
  jpa:
    show-sql: false
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///everything-project-db?cloudSqlInstance=everything-project-379518:europe-west6:everything-project-db-instance&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: app
    password: R]B%F*68J9Eq."i1
    hikari.data-source-properties:
      useSSL: true
      useUnicode: true
      socketTimeout: 1800000
      connectTimeout: 10000
      characterEncoding: utf8
      allowPublicKeyRetrieval: true
      jdbcCompliantTruncation: false
      createDatabaseIfNotExist: true
  liquibase:
    enabled: true
    drop-first: false
  cloud:
    gcp.sql:
      enabled: false

server:
  port: 8080
  servlet.session.timeout: 1800
  tomcat.accesslog.enabled: true
