spring:
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  jackson:
    serialization:
      indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everything_project
    username: root
    password: iseedeadpeople0197
    hikari:
      data-source-properties:
        useSSL: false
        useUnicode: true
        socketTimeout: 1800000
        connectTimeout: 10000
        characterEncoding: utf8
        allowPublicKeyRetrieval: true
        jdbcCompliantTruncation: false
        createDatabaseIfNotExist: true
  liquibase:
    enabled: true
    drop-first: false

server:
  port: 8080
  servlet:
    session:
      timeout: 1800
  tomcat:
    accesslog:
      enabled: true
