name: Is Version Incremented
on:
  - pull_request

#on:
#  push:
#    branches:
#      - feature/is-version-incremented-action
jobs:
  is-version-incremented:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git Diff
        run: |
               // if pull-request
               base="${{ github.event.pull_request.base.ref }}"
               head="${{ github.event.pull_request.head.ref }}"
               git fetch origin ${base}:refs/remotes/origin/${base}
          // if pom.xml
               path=$(git diff --name-only origin/${base} | grep pom.xml)
               if [ -z "${path}" ]
               then
               echo "Cannot find pom.xml in changed files"
               exit 1
               else
               diff=$(git diff origin/${base} ${path} | | sed -e 's| ||g')
               was=$(echo "${diff}" \
               | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
               become=$(echo "${diff}" \
               | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
               echo "WAS -- ${was}"
               echo "become -- ${become}"
               fi



#          echo ${{ github.event.pull_request.base.ref }}
#          echo ${{ github.event.pull_request.head.ref }}
#          more $GITHUB_EVENT_PATH
