name: Is Version Incremented
on:
  - pull_request

#on:
#  push:
#    branches:
#      - feature/is-version-incremented-action
jobs:
  is-version-incremented:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git Diff
        run: |
          base="${{ github.event.pull_request.base.ref }}"
          head="${{ github.event.pull_request.head.ref }}"
          git fetch origin/${base}
          git diff --name-only origin/${base}
#          echo ${{ github.event.pull_request.base.ref }}
#          echo ${{ github.event.pull_request.head.ref }}
#          more $GITHUB_EVENT_PATH
