name: Is Version Incremented
on:
  push:
    branches:
      - feature/is-version-incremented-action
jobs:
  is-version-incremented:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git Diff
        run: |
          git diff --name-only
